package unfpa.shakawat.anc.model;

public class Pts {
    public  int id=0;
    public  int hos_num=0;
    public  String hos_name="";
    public  String num="";
    public  int age=0;
    public  int edu_year=0;
    public  String edu_oth_txt="";
    public  String ocu="";
    public  String hocu="";
    public  int income=0;
    public  String add="";
    public  String mob="";
    public  int dg=0;
    public  int child_num=0;
    public  String preg_comp_oth_txt="";
    public  String sm_oth_txt="";
    public  String pt_num="";
    public  String pt_doc="";
    public  int sc=0;
    public  int is_married=0;
    public  int live_husband=0;
    public  int edu=0;
    public  int have_child=0;
    public  int preg_comp=0;
    public  int pt_dis=0;
    public  int use_condom=0;
    public  int transmission=0;
    public  int sm_anc=0;
    public  int sm_vd=0;
    public  int sm_vi=0;
    public  int sm_lap=0;
    public  int sm_gu=0;
    public  int sm_pu=0;
    public  int sm_pi=0;
    public  int sm_oth=0;
    public  String sm_vd_day="";
    public  String sm_vi_day="";
    public  String sm_lap_day="";
    public  String sm_gu_day="";
    public  String sm_pu_day="";
    public  String sm_pi_day="";
    public  String sm_oth_day="";
    public  int multi_sex=0;
    public  String his_sti="";
}
